

parameters:
- name: environment
  displayName: Environment
  type: string
- name: ASPNETCORE_ENVIRONMENT
  displayName: 
  type: string
- name: CONNECTIONSTRINGS__DATABASE
  displayName: Connection string
  type: string
- name: dockerRepo
  displayName: Docker Repo
  type: string
- name: container
  displayName: Container
  type: string
- name: webAppName
  displayName: Web App Name
  type: string
- name: azureSubscription
  displayName: Azure subscription
  type: string

  

jobs:
- deployment: Deploy_To_${{ parameters.environment }}
  displayName: 'Deploying to ${{ parameters.environment }}'
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        
        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: $(azureSubscription)
            appName: $(webAppName)
            containers: $(container)
            appSettings: '-PORT 80 -ASPNETCORE_ENVIRONMENT ${{ parameters.ASPNETCORE_ENVIRONMENT}} -CONNECTIONSTRINGS__DATABASE ${{ parameters.CONNECTIONSTRINGS__DATABASE }}'
                          
        