trigger:
- develop
- feature/devops #Remove after testing

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'  
  - name: buildConfiguration
    value: 'Release'
  - name: dockerRepo
    value: 'kpreethamraj/sales-api'


stages:
 - stage: Build
   displayName: Build, Test & Dockerize
   jobs:
     - job: Build
       pool:
         vmImage: 'ubuntu-latest'
       displayName: Build API
       steps:
        - task: NuGetToolInstaller@1
          displayName: Install Nuget Tool
          inputs:
              checkLatest: true
              
        - task: NuGetCommand@2
          displayName: Nuget Restore
          inputs:
            command: 'restore'
            restoreSolution: $(solution)
            feedsToUse: 'select'
            
        - task: DotNetCoreCLI@2
          displayName: Unit tests 
          inputs:
            command: 'test'
            projects: '**/DevOpsChallenge.SalesApi.Business.UnitTests.csproj'
            testRunTitle: 'Unit tests'

        - task: DotNetCoreCLI@2
          displayName: Build API
          inputs:
            command: 'build'
            projects: '**/DevOpsChallenge.SalesApi.csproj'
        
        - task: Docker@2
          displayName: Container Registry Login
          inputs:
            containerRegistry: 'dockerHub'
            command: 'login'

        - task: Docker@2
          displayName: Containerize and push to hub
          inputs:
            containerRegistry: 'dockerHub'
            repository: $(dockerRepo)
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Build.BuildId)
                          
        - task: Docker@2
          displayName: Container Registry Logout
          inputs:
            containerRegistry: 'dockerHub'
            command: 'logout'