

parameters:
- name: environment
  displayName: Environment
  type: string
- name: ASPNETCORE_ENVIRONMENT
  displayName: 
  type: string
- name: dockerRepo
  displayName: Docker Repo
  type: string
- name: container
  displayName: Container
  type: string
- name: webAppName
  displayName: Web App Name
  type: string
- name: azureSubscription
  displayName: Azure subscription
  type: string
- name: keyVault
  displayName: Azure Key Vault
  type: string

  

jobs:
- deployment: Deploy_To_${{ parameters.environment }}
  displayName: 'Deploying to ${{ parameters.environment }}'
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:       
                
        - task: AzureKeyVault@1
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            KeyVaultName: ${{ parameters.keyVault }}
            SecretsFilter: '*'
            RunAsPreJob: true
        
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              $v= [Environment]::GetEnvironmentVariable("connectionString-$environment:Environment")
              Write-Host $v
              Write-Host ("##vso[task.setvariable variable=connectionString;isSecret=true]$v")

        
        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appName: ${{ parameters.webAppName }}
            containers: ${{ parameters.container }}
            appSettings: '-PORT 80 -ASPNETCORE_ENVIRONMENT ${{ parameters.ASPNETCORE_ENVIRONMENT}} -CONNECTIONSTRINGS__DATABASE $(connectionString)'
                          
        # DB Migrations!
        # This can get tricky in a teams setting. Leaving it for now.
        #- task: Bash@3
        #  inputs:
        #    targetType: 'inline'
        #    script: |
        #      dotnet tool install -g dotnet-ef
        #      dotnet ef database update
        #    failOnStderr: true
        #    noProfile: false
        #    noRc: false
