version: "3.8" 
services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DATABASE=Server=db;Database=DevOpsChallenge.SalesApi;user=sa;Password=Preetham!12345
      
    ports:
      - "0.0.0.0:2222:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=Preetham!12345
    ports:
      - "1433:1433"

 